#pragma once

#define ST7789 1
#define ST7789VW 1
#define GPIO_TFT_DATA_CONTROL 6
#define GPIO_TFT_RESET_PIN 5
#define GPIO_TFT_BACKLIGHT 13
#define SPI_BUS_CLOCK_DIVISOR 20
// #define SPI_BUS_CLOCK_DIVISOR 30
// #define USE_DMA_TRANSFERS 0
// #define DISPLAY_ROTATE_180_DEGREES 1

#define DISPLAY_SET_CURSOR_X 0x2A
#define DISPLAY_SET_CURSOR_Y 0x2B
#define DISPLAY_WRITE_PIXELS 0x2C

#define DISPLAY_WIDTH 240
#define DISPLAY_HEIGHT 240

#define DISPLAY_SPI_DRIVE_SETTINGS (1 | BCM2835_SPI0_CS_CPOL | BCM2835_SPI0_CS_CPHA)

#define SPI_BYTESPERPIXEL 2
